import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers"
import NavBar from "./component/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en"
      suppressHydrationWarning>
np
      <body>
        <Providers>
          <NavBar />
          
             {children}
        </Providers>
    
      </body>
    </html>
  );
}

